### PR TITLE
Update Easy_038_Count_And_Say.swift

### PR DESCRIPTION
**Pull request by dimpiax**
Hi, check my implementation please

### CODE REVIEW

**Comment by diwu** [comment]
You can test your own implementation by replacing the original implementation through copy and paste and run the XCTest build scheme. When you do, you'll see that your algorithm fails 2 out of [all 3 test cases](https://github.com/diwu/LeetCode-Solutions-in-Swift/blob/master/Solutions/SolutionsTests/Easy/Easy_038_Count_And_Say_Test.swift).

**Comment by dimpiax** [comment]
related to this description: https://leetcode.com/problems/count-and-say/ results of my solution works right, where in description described that "8 must be 31131211131221" – I don't see.

About your code:
it produces "11 – 3113112221232112111312211312113211", when in description goal is next: 
11 is read off as "two 1s" or 21.

**Comment by diwu** [comment]
The problem description is misleading. You may have misunderstood the problem. Please take a look at [@HongbiaoYang](https://leetcode.com/discuss/3972/please-change-the-misleading-description) and [@wutingyehe](https://leetcode.com/discuss/3972/please-change-the-misleading-description)'s comments at the LeetCode forum.

> "I solved the wrong problem also, thought was to "say" the given integer input. After several times of reading the question I understood it in the end. I think we need an example of input/output test case, like input 5, output "111221", so we know we are not expecting "15" as the result."
> 
> "I think it's better to offer more examples, such as: if n = 4, the sequence is "111221"; if n = 5, the sequence is "312211"."

**Comment by dimpiax** [comment]
yes, description is weird so.
why your code of 11 – produces that long number?

**Comment by diwu** [comment]
The length of the result gets bloated pretty quickly. The really long number you see might in fact be correct.

**Comment by dimpiax** [comment]
was good discussion, good luck diwu!

**Pull request closed without merging**
